server:
    port: 8080
    error:
        include-message: always

logging:
    level:
        root: INFO
        com.example: DEBUG

spring:
    config:
        activate:
            on-profile: default

app:
    employee-service:
        host: localhost
        port: 8082

    customers-service:
        host: localhost
        port: 8081


    book-service:
         host: localhost
         port: 8083

